baseURL = "http://example.org/"
# 设置默认的语言
defaultContentLanguage = "zh-cn"
# 网站语言，仅在这里CN大写
languageCode = "zh-CN"
# 是否包含中日韩文字
hasCJKLanguage = true
# 网站标题
title = "Gez's Testing Blog"

# 更改使用 Hugo 构建网站时使用的默认主题
theme = "LoveIt"

[params]
  # LoveIt 主题版本
  version = "0.2.X"
  # 网站描述
  description = "这是Gez的 Testing 博客"
  # 网站关键词
  keywords = ["Testing", "Hugo", "软件测试", "计算机基础", "自学测试", "测试基础", "初级测试"]
  # 网站默认主题样式 ("light", "dark", "auto")
  defaultTheme = "auto"
# 公共 git 仓库路径，仅在 enableGitInfo 设为 true 时有效
#gitRepo = ""
# LoveIt 新增 | 0.1.1 哪种哈希函数用来 SRI, 为空时表示不使用 SRI
# ("sha256", "sha384", "sha512", "md5")
#fingerprint = ""
# LoveIt 新增 | 0.2.0 日期格式
#dateFormat = "2006-01-02"
# 网站图片, 用于 Open Graph 和 Twitter Cards
images = ["/logo.png"]

# LoveIt 新增 | 0.2.0 应用图标配置
[params.app]
  # 当添加到 iOS 主屏幕或者 Android 启动器时的标题, 覆盖默认标题
  title = "Gez's Testing"
  # 是否隐藏网站图标资源链接
  noFavicon = false
  # 更现代的 SVG 网站图标, 可替代旧的 .png 和 .ico 文件
  svgFavicon = ""
  # Android 浏览器主题色
  themeColor = "#ffffff"
  # Safari 图标颜色
  iconColor = "#5bbad5"
  # Windows v8-10磁贴颜色
  tileColor = "#da532c"

# LoveIt 新增 | 0.2.0 搜索配置
[params.search]
  enable = true
  # 搜索引擎的类型 ("lunr", "algolia")
  type = "lunr"
  # 文章内容最长索引长度
  contentLength = 4000
  # 搜索框的占位提示语
  placeholder = "想搜啥"
  # LoveIt 新增 | 0.2.1 最大结果数目
  maxResultLength = 10
  # LoveIt 新增 | 0.2.3 结果内容片段长度
  snippetLength = 50
  # LoveIt 新增 | 0.2.1 搜索结果中高亮部分的 HTML 标签
  highlightTag = "em"
  # LoveIt 新增 | 0.2.4 是否在搜索索引中使用基于 baseURL 的绝对路径
  absoluteURL = false
[params.search.algolia]
  index = ""
  appID = ""
  searchKey = ""

# 页面头部导航栏配置
[params.header]
  # 桌面端导航栏模式 ("fixed", "normal", "auto")
  desktopMode = "fixed"
  # 移动端导航栏模式 ("fixed", "normal", "auto")
  mobileMode = "auto"
  # LoveIt 新增 | 0.2.0 页面头部导航栏标题配置
  [params.header.title]
    # LOGO 的 URL
    logo = "/images/potter_sorting_hat_harry_magic_colour.png"
    # 标题名称
    name = "Gez's Testing"
    # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
    #pre = ""
    # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
    #post = ""
    # LoveIt 新增 | 0.2.5 是否为标题显示打字机动画
    typeit = false

# 页面底部信息配置
[params.footer]
  enable = true
  # LoveIt 新增 | 0.2.0 自定义内容 (支持 HTML 格式)
  #custom = ''
  # LoveIt 新增 | 0.2.0 是否显示 Hugo 和主题信息
  hugo = false
  # LoveIt 新增 | 0.2.0 是否显示版权信息
  copyright = true
  # LoveIt 新增 | 0.2.0 是否显示作者
  author = true
  # 网站创立年份
  since = 2022
    # ICP 备案信息，仅在中国使用 (支持 HTML 格式)
    #icp = ""
    # 许可协议信息 (支持 HTML 格式)
    #license =

# LoveIt 新增 | 0.2.0 Section (所有文章) 页面配置
[params.section]
  # section 页面每页显示文章数量
  paginate = 20
  # 日期格式 (月和日)
  dateFormat = "01-02"
  # RSS 文章数目
  rss = 10

# 主页配置
[params.home]
  # LoveIt 新增 | 0.2.0 RSS 文章数目
  rss = 10
  # 主页个人信息
  [params.home.profile]
    enable = true
    # Gravatar 邮箱，用于优先在主页显示的头像
    #gravatarEmail = "gez_ztt@163.com"
    # 主页显示头像的 URL
    avatarURL = "/images/头像.jpg"
    # LoveIt 更改 | 0.2.7 主页显示的网站标题 (支持 HTML 格式)
    #title = ""
    # 主页显示的网站副标题
    subtitle = "这是小郑的魔法世界"
    # 是否为副标题显示打字机动画
    typeit = true
    # 是否显示社交账号
    social = true
    # LoveIt 新增 | 0.2.0 免责声明 (支持 HTML 格式)
    #disclaimer = ""
  # 主页文章列表
  [params.home.posts]
    enable = true
    # 主页每页显示文章数量
    paginate = 6
    # 当你没有在文章前置参数中设置 "hiddenFromHomePage" 时的默认行为
    defaultHiddenFromHomePage = false

# 作者的社交信息设置
[params.social]
  GitHub = "Gez-GitHub"
  #Linkedin = ""
  #Twitter = "xxxx"
  #Instagram = "xxxx"
  #Facebook = "xxxx"
  #Telegram = "xxxx"
  #Youtubelegacy = ""
  #Youtubecustom = ""
  #Youtubechannel = ""
  #Reddit = ""
  #Weibo = ""
  #Skype = ""
  Whatsapp = ""
  Zhihu = ""
  Douban = ""
  Bilibili = ""
  Email = "gez_ztt@163.com"
  #RSS = true # LoveIt 新增 | 0.2.0

# LoveIt 更改 | 0.2.0 文章页面配置
[params.page]
  # LoveIt 新增 | 0.2.0 是否在主页隐藏一篇文章
  #hiddenFromHomePage = false
  # LoveIt 新增 | 0.2.0 是否在搜索结果中隐藏一篇文章
  #hiddenFromSearch = false
  # LoveIt 新增 | 0.2.0 是否使用 ruby 扩展语法
  ruby = true
  # LoveIt 新增 | 0.2.0 是否使用 fraction 扩展语法
  fraction = true
  # LoveIt 新增 | 0.2.0 是否使用 fontawesome 扩展语法
  fontawesome = true
  # 是否在文章页面显示原始 Markdown 文档链接
  linkToMarkdown = true
  # LoveIt 新增 | 0.2.4 是否在 RSS 中显示全文内容
  rssFullText = false
  # LoveIt 新增 | 0.2.0 目录配置
  [params.page.toc]
    # 是否使用目录
    enable = true
    # LoveIt 新增 | 0.2.9 是否保持使用文章前面的静态目录
    keepStatic = true
    # 是否使侧边目录自动折叠展开
    auto = true
  # LoveIt 新增 | 0.2.0 代码配置
  [params.page.code]
    # 是否显示代码块的复制按钮
    copy = true
    # 默认展开显示的代码行数
    maxShownLines = 10
  # LoveIt 新增 | 0.2.0 Mapbox GL JS 配置
  [params.page.mapbox]
    # Mapbox GL JS 的 access token
    accessToken = ""
    # 浅色主题的地图样式
    lightStyle = "mapbox://styles/mapbox/light-v9"
    # 深色主题的地图样式
    darkStyle = "mapbox://styles/mapbox/dark-v9"
    # 是否添加 NavigationControl
    navigation = true
    # 是否添加 GeolocateControl
    geolocate = true
    # 是否添加 ScaleControl
    scale = true
    # 是否添加 FullscreenControl
    fullscreen = true
  # LoveIt 更改 | 0.2.0 文章页面的分享信息设置
  [params.page.share]
    enable = true
    Whatsapp = true
    Reddit = false
    Weibo = true
    Renren = false
    Blogger = true
    Baidu = false
    Evernote = true
    Skype = false
  # 页面 SEO 配置
  [params.page.seo]
    # image URL
    # 图片 URL
    images = []
    # Publisher info
    # 出版者信息
    [params.page.seo.publisher]
      name = "xxxx"
      logoUrl = "/images/hogwarts_potter_colour_harry_castle.png"

[menu]
  [[menu.main]]
    identifier = "posts"
    # 可以在名称之前添加其他信息，例如图标
    pre = ""
    # 可以在名称之后添加其他信息，例如图标
    #post = ""
    name = "所有文章"
    url = "/posts/"
    # 当鼠标悬停在此菜单链接上时，将显示的标题
    title = "查看所有文章"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    title = "按标签查看文章"
    weight = 2
  [[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    title = "按类别查看文章"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    title = "关于Gez's Testing Blog"
    weight = 4


# Hugo 解析文档的配置
[markup]
  # 语法高亮设置
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    # false 是必要的设置
    # (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  # Goldmark 是 Hugo 0.60 以来的默认 Markdown 解析库
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # 是否在文档中直接使用 HTML 标签
      unsafe = true
  # 目录设置
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

# 作者配置
[author]
  name = "小郑"
  email = "gez_ztt@163.com"

# 用于输出 Markdown 格式文档的设置
[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

# 用于输出 Markdown 格式文档的设置
[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false